### ISSUE TITLE
Snippet editor (Ace editor) does not work on mobile

### ISSUE THREAD

**Issue by benjaminheng** [wryyl/snipbase#1]
**Problem:** Each character overrides the previous character, leaving the user unable to type.
**Suggested solution:** Do a check if the user is on mobile. If on mobile, do not render the ace editor over the textarea. The user can then input text into the textarea.

**Comment by TimothyTam** [comment]
As of 6f3f8d8:
Text area is not hidden by default
If it is not a mobile device, ace editor will replace text area
