### ISSUE TITLE
Selective redirect when deleting snippet.

### ISSUE THREAD

**Issue by benjaminheng** [wryyl/snipbase#2]
**Current:** User is redirected to add_snippet_path after successful deletion of snippet.
**Proposed:** Only redirect user if user is deleting from the "edit snippet" page. Otherwise the page should simply refresh 'shared/messages'.

**Comment by TimothyTam** [comment]
done

**Comment by benjaminheng** [comment]
Added in 85bb2a6492f43b20062bbdfe03f62c468754537d, 6f41df4eab93d72a8c33421fb23259e0feafdab1, ccebe95bc3d3dd8c8c6de665d42373bf49af2c5b
