### ISSUE TITLE
Unauthorized users can edit/delete snippets

### ISSUE THREAD

**Issue by benjaminheng** [wryyl/snipbase#5]
**Steps:**
- Log into user1
- Visit user2's profile
- Edit or delete user2's snippet

**Proposed solution:** 
- Modify snippet template to not show the edit/delete controls if `current_user != snippet.user`.
- Modify `snippets_controller` to do an authorization check

**Comment by TimothyTam** [comment]
Made snippets to be editable/deletable only by owner for now.

**Comment by benjaminheng** [comment]
Fixed in da8f9d605dcc0d96fd4d78439db3df5bfcac138e and ccebe95bc3d3dd8c8c6de665d42373bf49af2c5b
